apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: ray-test
  namespace: flux-system
spec:
  url: ssh://git@github.com/utsavv27/supatest.git
  interval: 5m0s
  ref:
    branch: main
  secretRef:
    name: supabase
  ignore: |
    # exclude all
    /*
    # include primary-3 dir
    !/supabase
